# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
# use_frameworks!

target 'TestCocoaPods' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'ZipArchive', '~> 1.4.0'

  # Pods for TestCocoaPods

  target 'TestCocoaPodsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestCocoaPodsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
